### ISSUE TITLE
Example imports don't work when installing from pypi or gihub

### ISSUE THREAD

**Issue by TomCallan** [jonmest/thumos-stock-screener#3]
After installing from pypi I'm left with 'ModuleNotFoundError'. Tried installing the github source but had the same problems.

Just noticed this occurs when trying to import the .lib part of the module, perhaps this is missing from the distribution?

**Comment by jonmest** [comment]
This has been resolved in the most recent PyPi package: https://pypi.org/project/thumos-stock-screener
